### PR TITLE
Alumni Update 2019-07-15

### PR DESCRIPTION
**Pull request by ajott**
Updated the alumni board page with blurbs for the board members, and removed the defunct committees.

Copyedited the history a bit ("seeds of brotherhood"? Eeewww)

Added some detail and a photo to the alumni reunion page

### CODE REVIEW

**Review by raveious — CHANGES_REQUESTED** [review]
Please include the reunion image locally into `/assets`, and a higher resolution one. The one that you are linking to is only 672x283, almost like it was a Facebook preview or something.

**Comment by raveious** [comment]
> Please include the reunion image locally into `/assets`, and a higher resolution one. The one that you are linking to is only 672x283, almost like it was a Facebook preview or something.

Looks like you uploaded the picture, but the web page doesn't refer to it.

**Comment by ajott** [comment]
The banner images for pi-mile et al also used imgur links rather than locally hosted files. I can re-submit with the change.

**Comment by ajott** [comment]
Upon further investigation, that looks to be the highest definition available for that particular photo.

**Comment by raveious** [comment]
> The banner images for pi-mile et al also used imgur links rather than locally hosted files. I can re-submit with the change.

I'll open a pull request for that soon.

**Review by raveious — CHANGES_REQUESTED** [review]
`https://infoupdate.mtutriangle.org` won't resolve due to what HTTPS does behind the scenes with TLS certs, but it does seem to redirect correctly with an HTTP link instead. Please change the url to an HTTP url instead, most browsers will attempt to switch after the redirect anyways. This doesn't work because the `infoupdate` subdomain is a redirect url, and not an actual subdomain.

**Review by raveious — APPROVED** [review]

**Pull request merged**
